version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1.3.15
jobs:
  # each new job gets it own container
  rspec:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.0
    steps:
      - checkout
      - run: ~/project/ci/setup-env.sh
      - run: ~/project/rspec.sh
  rubocop:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.0
    steps:
      - checkout
      - run: ~/project/ci/setup-env.sh
      - run: ~/project/rubocop.sh
  basic_shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
workflows:
  version: 2
  ruby_tests:
    jobs:
      - rspec
      - rubocop
  shellcheck:
    jobs:
      - basic_shellcheck
      - shellcheck/check