version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: ~/project/rspec.sh
  rubocop:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: ~/project/rubocop.sh
workflows:
  version: 2
  one_and_two:
    jobs:
      - rspec
      - rubocop