version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.0-node
    steps:
      - checkout
      - run: ~/project/rspec.sh
  rubocop:
    docker:
      - image: circleci/ruby:2.6.0-node
    steps:
      - checkout
      - run: ~/project/rubocop.sh
workflows:
  version: 2
  ruby_tests:
    jobs:
      - rspec
      - rubocop