version: 2
orbs:
  shellcheck: circleci/shellcheck@1.3.15
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.0
    steps:
      - checkout
      - run: ~/project/rspec.sh
  rubocop:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.0
    steps:
      - checkout
      - run: ~/project/rubocop.sh
workflows:
  version: 2
  ruby_tests:
    jobs:
      - rspec
      - rubocop
  shellcheck:
    jobs:
      - shellcheck