version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: find . -name circleci101
      # - run: rspec.sh
  rubocop:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: find . -name circleci101
      # - run: rubocop.sh
workflows:
  version: 2
  one_and_two:
    jobs:
      - rspec
      - rubocop