version: 2
orbs:
  shellcheck: circleci/shellcheck@1.3.15
jobs:
  script_checks:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.0
    steps:
      - checkout
      - run:  
          name: rspec
          command: ~/project/rspec.sh
      - run: 
          name: rubocop
          command: ~/project/rubocop.sh
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
workflows:
  version: 2
  verify_scripts:
    jobs:
      - script_checks